inherit_from: .rubocop_todo.yml
require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'lib/tasks/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/admin/**/*

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/AbcSize:
  Max: 20
