name: Liters and tests. # TODO: rename your action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Database
        run: |
          bundle exec rails db:create db:migrate

      - name: Run Rubocop
        run: |
          bundle exec rubocop
      
      - name: Run Reek
        run: |
          bundle exec reek

      - name: Run Rails Best Practices
        run: |
          bundle exec rails_best_practices

      - name: Run Brakeman
        run: |
          bundle exec brakeman -q -w2

      - name: Run Tests
        run: |
          bundle exec rspec
